### PR TITLE
Minor UI Refresh and Help Page

### PR DESCRIPTION
**Pull request by imattau**
UI Refresh and initial development of a Help page using a WebView

### CODE REVIEW

**Comment by jasoncheng** [comment]
I'm so happy that @imattau join us to the big help on DiCa,
i reviewed commits, lot of changes (Compose Dialog / TitleBar..and more), 
thanks for you hard work, and i like it, appreciate, 

From your commits,  look like you work on android development / design for years, am i right? i believe DiCa will getting better and better since you join.

some question list below.

1. Please reset [app/build.gradle](https://github.com/jasoncheng/dica/blob/d309e8f916b0260bb1660a5dead213736229c1da/app/build.gradle#L22) to original develop commit, because it's you workspace directory , should i put release key on Github? or just mail key to you. BTW, signingConfigs.jason, i would change to signingConfigs.dica

2. Help page's floating email icon click action, could you link to [DiCa support forum](https://meld.de/network?f=&cid=195750), or you have better idea on this?

3. Help page's variable ([dataString](https://github.com/imattau/dica/commit/d309e8f916b0260bb1660a5dead213736229c1da#diff-911b30c8a042f006888d151f3bf4bf6fR32)) should put it in assets/ or in locale ; BTW, this page is good to have :)

4. Status title bar background color, i'm not get used to after testing a hours, but it's not fair, because i not a professional, do you mind i [build a temp APK file](https://drive.google.com/open?id=17HH6u4yb1qsoJqSitsZeSWgYfiBgwEl8), and put it in DiCa forum, let user decide? is that okay?

**Comment by imattau** [comment]
Hi Jason,

Thanks for your feedback!
1. I've restored your config settings in the build file. + my own key so Android Studio would build.

2. Can make it link to the forum if you like, or could just remove it and have all the links inside the webview.

3. Moved to dataString value to @string/menu_help_text asset. It was hardcoded before because of a compile issue.

4. Can change the colour if you like, maybe to a lighter colour? I think it just needed something to help seperate the posts.

I've also add a Search link in the menu; which opens the existing SearchActivity.

**Comment by imattau** [comment]
If you can send me the signing key, that would be helpful. imatt.au@protonmail.com

**Comment by ghost** [comment]
I am glad and grateful to have imattau on board who is also an Andriod developer and helps to advance Friendca.
I preferred DiCa from the beginning because it was clear and intuitive to use from the very first minute, and so it has to stay that way.
The changes sound good and I'm ready for testing.

@imattau are you already registered on meld.de?

**Comment by jasoncheng** [comment]
@imattau https://abhiandroid.com/androidstudio/add-local-html-file-android-studio.html

**Comment by imattau** [comment]
> @imattau https://abhiandroid.com/androidstudio/add-local-html-file-android-studio.html

Even easier! And now could include images easily...

**Comment by jasoncheng** [comment]
> If you can send me the signing key, that would be helpful. [imatt.au@protonmail.com](mailto:imatt.au@protonmail.com)

Sent

**Comment by jasoncheng** [comment]
https://photos.app.goo.gl/dt1Kb9vszk7YYvSH9


Remove blank space, below editview

**Comment by imattau** [comment]
@jasoncheng found the problem. There was a maxline set to 6...

**Comment by jasoncheng** [comment]
each status bar background color(#e8eaf6 ) and rounded corner (as light as you can)

materializecss.com/color.html

**Comment by jasoncheng** [comment]
> @jasoncheng found the problem. There was a maxline set to 6...

Please do not set  too height to cover background message, 
sometimes we need to see background text , 
for easy reply a comment

**Comment by imattau** [comment]
@copiis No, on a different instance.

**Comment by jasoncheng** [comment]
Please, next time, do not push so many feature and enhancement in a same PR; I would prefer pick below list first for next release.

**1. Localization correction
2. Help page
3. Action Icon without text** ( Like / Retweet / Comments ..)

The rest part. i would keep it original look like for now, I think it's change too much, such as : 

- Profile page, add friend, this function , API even not ready yet (could hidden for later use)

- Search function , API have performance issue, user will complain on this, because sometimes, it's search for nothing, and also, it's only support when friendica 2019-03-RC release, not ready yet. That's why only #hashtag clickable.

- Background color, it's did separate, but , after two days testing. it's make my eyeballs no comfortable, even lot of color I did changed, even i use super lighted background color and also rounded corner, it's still every where that i can't handle; Navigation ActionBar and Background color for status bar, both i prefer keep it blank white for now.

- Profile page background color, can be use Palette class, it's awesome, dynamic extract user avatar primary background color and text color which fit in avatar, then each user have different style. Maybe you can take a look at it: https://developer.android.com/training/material/palette-colors

In this situation, I really don't know how to take this PR, it's complicated;
I would take PR and modify some enhancement rollback to originally.

then marge into develop branch, once I done, let's move forward on it.

Hope you understand.

Recently, busy for my new job, will take this action next week
(during my Chinese new year vocation ), or would you mind submit a new PR include just those there features that i list above ?

**Comment by imattau** [comment]
Only think not changed it the colours.

**Comment by jasoncheng** [comment]
> Only think not changed it the colours.

revert original comment dialog too, thanks

**Pull request merged**
